### PR TITLE
Update RPI GLES/EGL library names

### PR DESCRIPTION
**Pull request by psyke83**
Fixes stretch compatibility.

### CODE REVIEW

**Comment by joolswills** [comment]
the problem with merging this now, is anyone who hasn't updated the underlying OS is going to have problems. I think it might be worth waiting until after doing another updated image, before merging these.

Note that the ticket on RetroPie-Setup was assigned to me, and we are duplicating work. Can you please discuss changes before doing PR so we don't both work on the same things.

**Comment by psyke83** [comment]
Will do. I'll hold off on sending any more PRs until things settle.

This particular change most likely won't break jessie. The libbrcm libraries have been packaged in parallel with the originally-named files for some time to ease transition.

**Comment by psyke83** [comment]
To be precise: the libbrcm libraries were first included in libraspberrypi0_1.20160921-1_armhf.deb. So retropie installations using older firmware would be the cutoff.

**Comment by joolswills** [comment]
There is already one user who reported Kodi not working for this very reason. I can assure you there will be people this will affect. At least with a new image announced, I can detail that people need to update the OS packages first. I may also adjust retropie-setup to enforce underlying OS changes for example.

**Pull request closed without merging**
